#ifndef OFFBYNULL_ALIGNER_BACKTRACKERS_SLICEABLE_PAIRWISE_ALIGNMENT_GRAPH_BACKTRACKER_PATH_CONTAINER_ELEMENT_H
#define OFFBYNULL_ALIGNER_BACKTRACKERS_SLICEABLE_PAIRWISE_ALIGNMENT_GRAPH_BACKTRACKER_PATH_CONTAINER_ELEMENT_H

#include "offbynull/utils.h"
#include "offbynull/aligner/backtrackers/sliceable_pairwise_alignment_graph_backtracker/backtrackable_edge.h"

namespace offbynull::aligner::backtrackers::sliceable_pairwise_alignment_graph_backtracker::path_container::element {
    using offbynull::aligner::backtrackers::sliceable_pairwise_alignment_graph_backtracker::backtrackable_edge::backtrackable_edge;

    PACK_STRUCT_START
    /**
     * Edge within an
     * @ref offbynull::aligner::backtrackers::sliceable_pairwise_alignment_graph_backtracker::path_container::path_container::path_container.
     *
     * @tparam E Graph edge identifier type.
     */
    template<backtrackable_edge E>
    struct element {
        /** Point to previous entry in the linked list (edge before this edge). */
        element<E>* prev {};
        /** Point to next entry in the linked list (edge before this edge). */
        element<E>* next {};
        /** Edge identifier. */
        E backtracking_edge {};

        element() = default;  // TODO: Isn't this generated by default?

        bool operator==(const element &) const = default;  // TODO: Isn't this generated by default?
    }
    PACK_STRUCT_STOP;
}

#endif //OFFBYNULL_ALIGNER_BACKTRACKERS_SLICEABLE_PAIRWISE_ALIGNMENT_GRAPH_BACKTRACKER_PATH_CONTAINER_ELEMENT_H
